[package]
name = "metalogue"
version = "0.0.2"
publish = false # not yet!
edition = "2024"

[lib]
name = "metalogue"
crate-type = ["cdylib", "rlib"]

[dependencies]
objc2-metal = "0.3.2"
objc2 = "0.6.3"
objc2-foundation = "0.3.2"
block2 = "0.6.1"
dispatch2 = "0.3.0"
pyo3 = "0.27.2"

[dev-dependencies]
criterion = "0.8.1"

[[bench]]
name = "adder_kernel_compilation"
harness = false
