project:
  type: book

book:
  title: "Notes on Programming Apple Silicon"
  author: "Joey Carpinelli"
  date: "2026-01"
  date-format: "MMMM YYYY"

  chapters:
    - index.qmd
    - part: fundamentals/index.qmd
      chapters:
        - fundamentals/multi-device-programming.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    csl: https://raw.githubusercontent.com/citation-style-language/styles/refs/heads/master/association-for-computing-machinery.csl
    cover-image: https://secure-ecsd.elsevier.com/covers/80/Tango2/original/9780323912310.jpg
    theme:
      - cosmo
